markdown:         rdiscount
pygments:         true
paginate:         4

title:            Black Cube Theme
url:              http://www.pizn.me
feed:             /atom.xml
author:
    name:         Kumfo
    email:        kumfo@qq.com
description:      "Kumfo's Blog"

about: 			  "Kumfo,PHP 开发者"
follow:
    github:       https://github.com/pizn
    twitter:      http://www.twitter.com/piznlin
description:      "PIZn's blog theme -- Black Cube Theme 1.0 "


style: 			  /css/style.css
blogName: 		  Kumfo
blogDesc: 		  PHP开发者